/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
	address: "",
	electronOptions: {
		
	},
	ipWhitelist: [
		
	],
	language: "de",
	modules: [
		{
			module: "MMM-Remote-Control",
			position: "bottom_left",
			config: {
				
			}
		},
		{
			module: "alert",
			config: {
				
			}
		},
		{
			module: "updatenotification",
			position: "top_bar",
			config: {
				
			}
		},
		{
			module: "clock",
			position: "top_left",
			config: {
				
			}
		},
		{
			module: "calendar",
			header: "Feiertage",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.ifeiertage.de/rp-.ics"
					}
				],
				titleReplace: {
					"De verjaardag van ": "",
					"'s birthday": ""
				},
				excludedEvents: [
					
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third",
			config: {
				compliments: {
					anytime: [
						"Hey there sexy!"
					],
					morning: [
						"Guten Morgen!",
						"GenieÃŸe deinen Tag",
						"Wie hast du geschlafen?"
					],
					afternoon: [
						"Halloooo schÃ¶nheit!",
						"Du siehst heute verdammt gut aus!",
						"SchÃ¶n das du da bist."
					],
					evening: [
						"Du bist heiÃŸ!",
						"Du siehst gut aus!",
						"Welche eine Granate!",
						"Bei dir beschlage ich!"
					]
				}
			},
			header: ""
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",
				appid: "YOUR_OPENWEATHER_API_KEY",
				iconTable: {
					"01d": "wi-day-sunny",
					"02d": "wi-day-cloudy",
					"03d": "wi-cloudy",
					"04d": "wi-cloudy-windy",
					"09d": "wi-showers",
					"10d": "wi-rain",
					"11d": "wi-thunderstorm",
					"13d": "wi-snow",
					"50d": "wi-fog",
					"01n": "wi-night-clear",
					"02n": "wi-night-cloudy",
					"03n": "wi-night-cloudy",
					"04n": "wi-night-cloudy",
					"09n": "wi-night-showers",
					"10n": "wi-night-rain",
					"11n": "wi-night-thunderstorm",
					"13n": "wi-night-snow",
					"50n": "wi-night-alt-cloudy-windy"
				}
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",
				appid: "YOUR_OPENWEATHER_API_KEY",
				iconTable: {
					"01d": "wi-day-sunny",
					"02d": "wi-day-cloudy",
					"03d": "wi-cloudy",
					"04d": "wi-cloudy-windy",
					"09d": "wi-showers",
					"10d": "wi-rain",
					"11d": "wi-thunderstorm",
					"13d": "wi-snow",
					"50d": "wi-fog",
					"01n": "wi-night-clear",
					"02n": "wi-night-cloudy",
					"03n": "wi-night-cloudy",
					"04n": "wi-night-cloudy",
					"09n": "wi-night-showers",
					"10n": "wi-night-rain",
					"11n": "wi-night-thunderstorm",
					"13n": "wi-night-snow",
					"50n": "wi-night-alt-cloudy-windy"
				}
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Die Welt / Nachrichten",
						url: "http://www.tagesschau.de/xml/rss2"
					}
				],
				startTags: [
					
				],
				endTags: [
					
				]
			}
		}
	],
	paths: {
		modules: "modules",
		vendor: "vendor"
	}
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
